matrix:
  RUST: [stable, nightly]

steps:
  - name: Linux_x86_64
    image: rust
    when:
      event: [push, pull_request]
    commands:
      - rustup default $RUST
      - cargo check
      - cargo test

  - name: Linux_x86_64_nightly
    image: rust
    when: 
      event: [push, pull_request]
      - matrix: 
        RUST: nightly
    commands:
      - rustup default nightly
      - cargo check --features unsatable_preview
      - cargo test --features unsatable_preview
      
  - name: FreeBSD_15_x86_64
    image: freebsd/freebsd-runtime:15
    environment:
      RUST_BACKTRACE: 1
      HOME: /tmp # cargo caching needs it
    when:
      event: [push, pull_request]
    commands:
      - pkg install -y rust
      - cargo check
      - cargo build

