matrix:
  RUST: [stable, nightly]
  platform: 
    - linux/amd64
    - freebsd/amd64

steps:
  - name: Linux_x86_64
    image: rust
    when:
      - event: [push, pull_request]
        platform: linux/amd64
    commands:
      - rustup default $RUST
      - cargo check
      - cargo test

  - name: Linux_x86_64_nightly
    image: rust
    when: 
      - event: [push, pull_request]
        platform: linux/amd64
        matrix: 
          RUST: nightly
    commands:
      - rustup default nightly
      - rustup override set nightly
      - cargo check --features unsatable_preview
      - cargo test --features unsatable_preview

  - name: FreeBSD_x86_64
    image: rust
    when:
      - event: [push, pull_request]
        platform: freebsd/amd64
    commands:
      - rustup default $RUST
      - cargo check
      - cargo test
      
