matrix:
  RUST: [stable, nightly]
  PLATFORM:
    - linux/amd64
    - freebsd/amd64

steps:
  - name: FreeBSD_x86_64
    image: localhost/freebsd-runtime:latest
    pull: never
    when:
      - event: [push, pull_request]
        matrix:
          RUST: stable
          PLATFORM: freebsd/amd64
    commands:
      - echo "Running on $(uname -m)"
      - echo "Woodpecker Matrix Platform is ${PLATFORM}"
      - pkg add rust 
      - rustc --version
      - rustup default $RUST
      - cargo check
      - cargo test

