matrix:
  RUST: [stable, nightly]
  PLATFORM:
    - linux/amd64
    - freebsd/amd64

clone:
  - name: git
    image: localhost/woodpeckerci/plugin-git:latest
    settings: 
      platform: freebsd/amd64
      

steps:
  - name: FreeBSD_x86_64
    image: localhost/freebsd-runtime:15.0-RELEASE-amd64
    #pull: true
    when:
      - event: [push, pull_request]
        matrix:
          RUST: stable
          PLATFORM: freebsd/amd64
    commands:
      - echo "Running on $(uname -m)"
      - echo "Woodpecker Matrix Platform is ${PLATFORM}"
  #    - pkg add rust 
      - rustc --version
      - rustup default $RUST
      - cargo check
      - cargo test

