name: CI Rust UDS
on: [push, pull_request]

jobs:
  linux-test:
    runs-on: self-hosted 
    services:
      test-proxy:
      image: nginx:stable
      options: --add-host=host.docker.internal:host-gateway
      volumes: /vm_images:/vm_images
    steps:

      - uses: actions/checkout@v4

      - name: Test server
        run: |
          curl http://host.docker.internal

      - name: Check Rust Stable
        run: |
          echo "Running on Ubuntu!"
          rustc --version
          cargo check --tests --examples
          cargo build --tests --examples
          cargo test

# FreeeBSD          
  freebsd-test:
    needs: linux-test
    if: always()

    runs-on: self-hosted 
    container:
      image: registry:5000/ubuntu-vm:runner-24.04
      volumes:
        - /vm_images:/vm_images

    steps:
      - uses: actions/checkout@v6

      - name: Loop check
        run: |
          ls /dev | grep "kvm"
          ls /dev | grep "loop"

      - name: Start server background process
        run: |
          python3 -m http.server 8080 --directory /vm_images &
          sleep 2 # Give it a second to start

      - name: Test server
        run: |
          ls -ls /
          ls -la /vm_images
          curl --head http://localhost:8080/freebsd-15.0-x86-64.qcow2

      - name: Check Rust Stable FreeBSD
        uses: cross-platform-actions/action@v1.0.0
        with: 
          operating_system: freebsd
          image_url: http://localhost:8080/freebsd-15.0-x86-64.qcow2
          version: '15.0'
          shell: bash
          memory: 4G
          cpu_count: 3
          run: |
            uname -a
            whoami
            rustc --version
            cargo check --tests --examples
            cargo build --tests --examples
            cargo test

# OpenBSD
  openbsd-test:
    needs: freebsd-test
    if: always()

    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v6

      - name: Loop check
        run: |
          ls /dev | grep "(kvm|loop)"

      - name: Start server background process
        run: |
          python3 -m http.server 8080 --directory /vm_images &
          sleep 2 # Give it a second to start

      - name: Test server
        run: |
          ls -la /vm_images
          curl --head http://localhost:8080/openbsd-7.8-x86-64.qcow2

      - name: Check Rust Stable OpenBSD
        uses: cross-platform-actions/action@v1.0.0
        with: 
          operating_system: openbsd
          image_url: http://localhost:8080/openbsd-7.8-x86-64.qcow2
          version: '7.8'
          shell: bash
          memory: 4G
          cpu_count: 3
          run: |
            uname -a
            whoami
            rustc --version
            cargo check --tests --examples
            cargo build --tests --examples
            cargo test

# NetBSD ----
  netbsd-test:
    needs: openbsd-test
    if: always()

    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v6

      - name: Loop check
        run: |
          ls /dev | grep "(kvm|loop)"

      - name: Start server background process
        run: |
          python3 -m http.server 8080 --directory /vm_images &
          sleep 2 # Give it a second to start

      - name: Test server
        run: |
          ls -la /vm_images
          curl --head http://localhost:8080/netbsd-10.1-x86-64.qcow2

      - name: Check Rust Stable NetBSD
        uses: cross-platform-actions/action@v1.0.0
        with: 
          operating_system: netbsd
          version: '10.1'
          image_url: http://localhost:8080/netbsd-10.1-x86-64.qcow2
          shell: bash
          memory: 4G
          cpu_count: 3
          run: |
            uname -a
            whoami
            rustc --version
            cargo check --tests --examples
            cargo build --tests --examples
            cargo test
